name: Build release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run rollup
    - name: copy sensor files
      run: mkdir dist/custom_components && mkdir dist/custom_components/yerushamayim && cd src/sensor/ && cp __init__.py sensor.py manifest.json ../../dist/custom_components/yerushamayim
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Commit to dist
