name: Build release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run rollup
    - name: copy sensor files
      run: mkdir -p dist/custom_components && mkdir -p dist/custom_components/yerushamayim && cd src/sensor/ && cp __init__.py sensor.py manifest.json ../../dist/custom_components/yerushamayim
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Commit dist
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Create a GitHub release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.tag_version.outputs.new_tag }}
        name: Release ${{ steps.tag_version.outputs.new_tag }}
        body: ${{ steps.tag_version.outputs.changelog }}
    - name: update README.md
      run: sed "s/#-#-#VERSION#-#-#.*/### &#58;hammer_and_wrench&#58; Version&#58; ${{ steps.tag_version.outputs.new_tag }}/g" src/README-template.md > README.md
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Commit updated README.md
