name: Handle release

on:
  push:
    branches:
      - main
      - beta

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Create new release
        uses: googleapis/release-please-action@v4
        id: release
        with:
          # Use a different release type that supports pre-releases based on commit history
          release-type: simple
          # This is the crucial part:
          # Mark the release as a pre-release if the branch is 'beta'
          prerelease: ${{ github.ref_name == 'beta' }}

      - name: Checkout code if release was created
        uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}

      - name: Update README.md
        if: ${{ steps.release.outputs.release_created }}
        run: |
          # The tag_name output includes the 'v' prefix
          sed -i 's/Current version: .*/Current version: ${{ steps.release.outputs.tag_name }}/' README.md

      - name: Commit updated README.md
        if: ${{ steps.release.outputs.release_created }}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update version in README to ${{ steps.release.outputs.tag_name }}"
