name: Validate HACS

on:
  push:

jobs:
  validate-hacs-integration:
    runs-on: "ubuntu-latest"
    steps:
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"